### PR TITLE
Create service folders, add Edge python module sample

### PR DESCRIPTION
**Pull request by kgremban**
## Purpose
- Create folders to organize IoT Hub samples and IoT Edge samples
- Add the sample for https://docs.microsoft.com/azure/iot-edge/tutorial-python-module

## Does this introduce a breaking change?

```
[ ] Yes
[ X ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ X ] Other... Please describe: Add new sample
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by kgremban** [comment]
@yzhong94 Could you review this, please?

**Comment by yzhong94** [comment]
@kgremban Looks good to me.  Are you updating the MVC docs to reflect the change in root?

**Comment by kgremban** [comment]
@yzhong94 Yes, I just created PR https://github.com/MicrosoftDocs/azure-docs-pr/pull/41803 that I should be able to publish at 3pm today. Do you want me to notify you when that gets published, and then you can merge this to match?

**Comment by yzhong94** [comment]
Sounds good!  Thank you!

**Comment by kgremban** [comment]
@yzhong94 The changes have been published in the docs

**Pull request merged**
